// Autogenerated source file
// DO NOT MODIFY

#include "font.h"

static const u8 f6_font_char_32[] = { 0x00 };
static const u8 f6_font_char_33[] = { 0x2F };
static const u8 f6_font_char_34[] = { 0x6D, 0x01 };
static const u8 f6_font_char_35[] = { 0xEA, 0xAB, 0xAF, 0x00 };
static const u8 f6_font_char_36[] = { 0xAE, 0x38, 0xEA, 0x00 };
static const u8 f6_font_char_37[] = { 0x91, 0x24, 0x89};
static const u8 f6_font_char_38[] = { 0x52, 0x52, 0x0A };
static const u8 f6_font_char_39[] = { 0x07 };
static const u8 f6_font_char_40[] = { 0x56, 0x09 };
static const u8 f6_font_char_41[] = { 0xA9, 0x06 };
static const u8 f6_font_char_42[] = { 0xD5, 0x55 };
static const u8 f6_font_char_43[] = { 0x84, 0x7C, 0x42, 0x00 };
static const u8 f6_font_char_44[] = { 0x00, 0xAC, 0x00 };
static const u8 f6_font_char_45[] = { 0x00, 0x0F };
static const u8 f6_font_char_46[] = { 0x00, 0x0F };
static const u8 f6_font_char_47[] = { 0x80, 0x24, 0x01 };
static const u8 f6_font_char_48[] = { 0x6A, 0x5B, 0x01 };
static const u8 f6_font_char_49[] = { 0x9A, 0xA4, 0x03 };
static const u8 f6_font_char_50[] = { 0x96, 0x48, 0xF2};
static const u8 f6_font_char_51[] = { 0x8F, 0x86, 0x69};
static const u8 f6_font_char_52[] = { 0x64, 0xF5, 0x44};
static const u8 f6_font_char_53[] = { 0x1F, 0x87, 0x69};
static const u8 f6_font_char_54[] = { 0x16, 0x97, 0x69};
static const u8 f6_font_char_55[] = { 0x8F, 0x44, 0x22};
static const u8 f6_font_char_56[] = { 0x96, 0x96, 0x69};
static const u8 f6_font_char_57[] = { 0x96, 0xE9, 0x68};
static const u8 f6_font_char_58[] = { 0xCF, 0x03 };
static const u8 f6_font_char_59[] = { 0x36, 0xAC, 0x00 };
static const u8 f6_font_char_60[] = { 0x54, 0x44 };
static const u8 f6_font_char_61[] = { 0xF0, 0xF0};
static const u8 f6_font_char_62[] = { 0x11, 0x15 };
static const u8 f6_font_char_63[] = { 0x2A, 0x05, 0x01 };
static const u8 f6_font_char_64[] = { 0x96, 0xDD, 0x61};
static const u8 f6_font_char_65[] = { 0x96, 0xF9, 0x99};
static const u8 f6_font_char_66[] = { 0x97, 0x97, 0x79};
static const u8 f6_font_char_67[] = { 0x96, 0x11, 0x69};
static const u8 f6_font_char_68[] = { 0x97, 0x99, 0x79};
static const u8 f6_font_char_69[] = { 0x1F, 0x17, 0xF1};
static const u8 f6_font_char_70[] = { 0x1F, 0x17, 0x11};
static const u8 f6_font_char_71[] = { 0x96, 0xD1, 0xE9};
static const u8 f6_font_char_72[] = { 0x99, 0x9F, 0x99};
static const u8 f6_font_char_73[] = { 0x97, 0xA4, 0x03 };
static const u8 f6_font_char_74[] = { 0x88, 0x88, 0x69};
static const u8 f6_font_char_75[] = { 0x59, 0x33, 0x95};
static const u8 f6_font_char_76[] = { 0x11, 0x11, 0xF1};
static const u8 f6_font_char_77[] = { 0xF9, 0x9F, 0x99};
static const u8 f6_font_char_78[] = { 0xB9, 0xDB, 0x9D};
static const u8 f6_font_char_79[] = { 0x96, 0x99, 0x69};
static const u8 f6_font_char_80[] = { 0x97, 0x79, 0x11};
static const u8 f6_font_char_81[] = { 0x96, 0x99, 0x6B, 0x08 };
static const u8 f6_font_char_82[] = { 0x97, 0x79, 0x95};
static const u8 f6_font_char_83[] = { 0x96, 0x42, 0x69};
static const u8 f6_font_char_84[] = { 0x97, 0x24, 0x01 };
static const u8 f6_font_char_85[] = { 0x99, 0x99, 0x69};
static const u8 f6_font_char_86[] = { 0x99, 0x99, 0x66};
static const u8 f6_font_char_87[] = { 0x99, 0xF9, 0x9F};
static const u8 f6_font_char_88[] = { 0x99, 0x66, 0x99};
static const u8 f6_font_char_89[] = { 0x6D, 0x25, 0x01 };
static const u8 f6_font_char_90[] = { 0x8F, 0x24, 0xF1};
static const u8 f6_font_char_91[] = { 0x4F, 0x92, 0x03 };
static const u8 f6_font_char_92[] = { 0x10, 0x42, 0x08 };
static const u8 f6_font_char_93[] = { 0x27, 0xC9, 0x03 };
static const u8 f6_font_char_94[] = { 0x2A };
static const u8 f6_font_char_95[] = { 0x00, 0x00, 0xF0};
static const u8 f6_font_char_96[] = { 0x09 };
static const u8 f6_font_char_97[] = { 0x00, 0x9E, 0xAD};
static const u8 f6_font_char_98[] = { 0x11, 0x97, 0x79};
static const u8 f6_font_char_99[] = { 0x80, 0x13, 0x03 };
static const u8 f6_font_char_100[] = { 0x88, 0x9E, 0xE9};
static const u8 f6_font_char_101[] = { 0x00, 0xD6, 0x63};
static const u8 f6_font_char_102[] = { 0xA4, 0x72, 0x22};
static const u8 f6_font_char_103[] = { 0xE0, 0x69, 0xE1};
static const u8 f6_font_char_104[] = { 0x11, 0x97, 0x99};
static const u8 f6_font_char_105[] = { 0xC2, 0xA4, 0x03 };
static const u8 f6_font_char_106[] = { 0x04, 0xC9, 0x0A };
static const u8 f6_font_char_107[] = { 0x11, 0x35, 0x95};
static const u8 f6_font_char_108[] = { 0x93, 0xA4, 0x03 };
static const u8 f6_font_char_109[] = { 0x00, 0xF5, 0x99};
static const u8 f6_font_char_110[] = { 0x00, 0x97, 0x99};
static const u8 f6_font_char_111[] = { 0x00, 0x96, 0x69};
static const u8 f6_font_char_112[] = { 0x70, 0x99, 0x17};
static const u8 f6_font_char_113[] = { 0xE0, 0x99, 0x8E};
static const u8 f6_font_char_114[] = { 0x00, 0x97, 0x11};
static const u8 f6_font_char_115[] = { 0x00, 0x3E, 0x7C};
static const u8 f6_font_char_116[] = { 0x22, 0x27, 0xC2};
static const u8 f6_font_char_117[] = { 0x00, 0x99, 0xE9};
static const u8 f6_font_char_118[] = { 0x40, 0x5B, 0x01 };
static const u8 f6_font_char_119[] = { 0x00, 0x99, 0xFF};
static const u8 f6_font_char_120[] = { 0x00, 0x69, 0x96};
static const u8 f6_font_char_121[] = { 0x90, 0xA9, 0x24};
static const u8 f6_font_char_122[] = { 0x00, 0x4F, 0xF2};
static const u8 f6_font_char_123[] = { 0xD4, 0x24, 0x02 };
static const u8 f6_font_char_124[] = { 0x3F };
static const u8 f6_font_char_125[] = { 0x91, 0xA5, 0x00 };
static const u8 f6_font_char_126[] = { 0x00, 0x5A};

static const FONT_CHAR f6_chars[] = 
{
 { 32, 1, 1, f6_font_char_32 },
 { 33, 1, 6, f6_font_char_33 },
 { 34, 3, 3, f6_font_char_34 },
 { 35, 5, 5, f6_font_char_35 },
 { 36, 5, 5, f6_font_char_36 },
 { 37, 4, 6, f6_font_char_37 },
 { 38, 4, 5, f6_font_char_38 },
 { 39, 1, 3, f6_font_char_39 },
 { 40, 2, 6, f6_font_char_40 },
 { 41, 2, 6, f6_font_char_41 },
 { 42, 3, 5, f6_font_char_42 },
 { 43, 5, 5, f6_font_char_43 },
 { 44, 3, 6, f6_font_char_44 },
 { 45, 4, 3, f6_font_char_45 },
 { 46, 2, 6, f6_font_char_46 },
 { 47, 4, 5, f6_font_char_47 },
 { 48, 3, 6, f6_font_char_48 },
 { 49, 3, 6, f6_font_char_49 },
 { 50, 4, 6, f6_font_char_50 },
 { 51, 4, 6, f6_font_char_51 },
 { 52, 4, 6, f6_font_char_52 },
 { 53, 4, 6, f6_font_char_53 },
 { 54, 4, 6, f6_font_char_54 },
 { 55, 4, 6, f6_font_char_55 },
 { 56, 4, 6, f6_font_char_56 },
 { 57, 4, 6, f6_font_char_57 },
 { 58, 2, 5, f6_font_char_58 },
 { 59, 3, 6, f6_font_char_59 },
 { 60, 3, 5, f6_font_char_60 },
 { 61, 4, 4, f6_font_char_61 },
 { 62, 3, 5, f6_font_char_62 },
 { 63, 3, 6, f6_font_char_63 },
 { 64, 4, 6, f6_font_char_64 },
 { 65, 4, 6, f6_font_char_65 },
 { 66, 4, 6, f6_font_char_66 },
 { 67, 4, 6, f6_font_char_67 },
 { 68, 4, 6, f6_font_char_68 },
 { 69, 4, 6, f6_font_char_69 },
 { 70, 4, 6, f6_font_char_70 },
 { 71, 4, 6, f6_font_char_71 },
 { 72, 4, 6, f6_font_char_72 },
 { 73, 3, 6, f6_font_char_73 },
 { 74, 4, 6, f6_font_char_74 },
 { 75, 4, 6, f6_font_char_75 },
 { 76, 4, 6, f6_font_char_76 },
 { 77, 4, 6, f6_font_char_77 },
 { 78, 4, 6, f6_font_char_78 },
 { 79, 4, 6, f6_font_char_79 },
 { 80, 4, 6, f6_font_char_80 },
 { 81, 4, 7, f6_font_char_81 },
 { 82, 4, 6, f6_font_char_82 },
 { 83, 4, 6, f6_font_char_83 },
 { 84, 3, 6, f6_font_char_84 },
 { 85, 4, 6, f6_font_char_85 },
 { 86, 4, 6, f6_font_char_86 },
 { 87, 4, 6, f6_font_char_87 },
 { 88, 4, 6, f6_font_char_88 },
 { 89, 3, 6, f6_font_char_89 },
 { 90, 4, 6, f6_font_char_90 },
 { 91, 3, 6, f6_font_char_91 },
 { 92, 4, 5, f6_font_char_92 },
 { 93, 3, 6, f6_font_char_93 },
 { 94, 3, 2, f6_font_char_94 },
 { 95, 4, 6, f6_font_char_95 },
 { 96, 2, 2, f6_font_char_96 },
 { 97, 4, 6, f6_font_char_97 },
 { 98, 4, 6, f6_font_char_98 },
 { 99, 3, 6, f6_font_char_99 },
 { 100, 4, 6, f6_font_char_100 },
 { 101, 4, 6, f6_font_char_101 },
 { 102, 4, 6, f6_font_char_102 },
 { 103, 4, 6, f6_font_char_103 },
 { 104, 4, 6, f6_font_char_104 },
 { 105, 3, 6, f6_font_char_105 },
 { 106, 3, 7, f6_font_char_106 },
 { 107, 4, 6, f6_font_char_107 },
 { 108, 3, 6, f6_font_char_108 },
 { 109, 4, 6, f6_font_char_109 },
 { 110, 4, 6, f6_font_char_110 },
 { 111, 4, 6, f6_font_char_111 },
 { 112, 4, 6, f6_font_char_112 },
 { 113, 4, 6, f6_font_char_113 },
 { 114, 4, 6, f6_font_char_114 },
 { 115, 4, 6, f6_font_char_115 },
 { 116, 4, 6, f6_font_char_116 },
 { 117, 4, 6, f6_font_char_117 },
 { 118, 3, 6, f6_font_char_118 },
 { 119, 4, 6, f6_font_char_119 },
 { 120, 4, 6, f6_font_char_120 },
 { 121, 4, 6, f6_font_char_121 },
 { 122, 4, 6, f6_font_char_122 },
 { 123, 3, 6, f6_font_char_123 },
 { 124, 1, 6, f6_font_char_124 },
 { 125, 3, 6, f6_font_char_125 },
 { 126, 4, 4, f6_font_char_126 },
};

const FONT f6_font = { 95, f6_chars };
