// Autogenerated source file
// DO NOT MODIFY

#include "font.h"

static const u8 font5x5_font_char_32[] = { 0x00 };
static const u8 font5x5_font_char_33[] = { 0x17 };
static const u8 font5x5_font_char_34[] = { 0x2D };
static const u8 font5x5_font_char_35[] = { 0xEA, 0xAB, 0xAF, 0x00 };
static const u8 font5x5_font_char_36[] = { 0xE4, 0x97, 0x4F, 0x3F, 0x01 };
static const u8 font5x5_font_char_37[] = { 0x11, 0x11, 0x11, 0x01 };
static const u8 font5x5_font_char_38[] = { 0x26, 0xD8, 0x64, 0x01 };
static const u8 font5x5_font_char_39[] = { 0x03 };
static const u8 font5x5_font_char_40[] = { 0x56, 0x02 };
static const u8 font5x5_font_char_41[] = { 0xA9, 0x01 };
static const u8 font5x5_font_char_42[] = { 0xBA, 0x00 };
static const u8 font5x5_font_char_43[] = { 0x84, 0x7C, 0x42, 0x00 };
static const u8 font5x5_font_char_44[] = { 0x18 };
static const u8 font5x5_font_char_45[] = { 0x00, 0x7C };
static const u8 font5x5_font_char_46[] = { 0x10 };
static const u8 font5x5_font_char_47[] = { 0xA4, 0x12 };
static const u8 font5x5_font_char_48[] = { 0x3F, 0xD7, 0xF9, 0x01 };
static const u8 font5x5_font_char_49[] = { 0x9A, 0x74 };
static const u8 font5x5_font_char_50[] = { 0x0F, 0xBA, 0xF0, 0x01 };
static const u8 font5x5_font_char_51[] = { 0x1F, 0x3A, 0xF8, 0x01 };
static const u8 font5x5_font_char_52[] = { 0x21, 0x94, 0x4F, 0x00 };
static const u8 font5x5_font_char_53[] = { 0x3F, 0x3C, 0xF8, 0x00 };
static const u8 font5x5_font_char_54[] = { 0x3F, 0xFC, 0xF8, 0x01 };
static const u8 font5x5_font_char_55[] = { 0x1F, 0x22, 0x42, 0x00 };
static const u8 font5x5_font_char_56[] = { 0x3F, 0xFE, 0xF8, 0x01 };
static const u8 font5x5_font_char_57[] = { 0x3F, 0x7E, 0xF8, 0x01 };
static const u8 font5x5_font_char_58[] = { 0x11 };
static const u8 font5x5_font_char_59[] = { 0x31 };
static const u8 font5x5_font_char_60[] = { 0x54, 0x44 };
static const u8 font5x5_font_char_61[] = { 0xE0, 0x83, 0x0F };
static const u8 font5x5_font_char_62[] = { 0x11, 0x15 };
static const u8 font5x5_font_char_63[] = { 0x96, 0x04, 0x04 };
static const u8 font5x5_font_char_64[] = { 0x3F, 0xF6, 0xF0, 0x01 };
static const u8 font5x5_font_char_65[] = { 0x3F, 0xC6, 0x1F, 0x01 };
static const u8 font5x5_font_char_66[] = { 0x3F, 0xBE, 0xF8, 0x01 };
static const u8 font5x5_font_char_67[] = { 0x3F, 0x84, 0xF0, 0x01 };
static const u8 font5x5_font_char_68[] = { 0x2F, 0xC6, 0xF8, 0x00 };
static const u8 font5x5_font_char_69[] = { 0x3F, 0xBC, 0xF0, 0x01 };
static const u8 font5x5_font_char_70[] = { 0x3F, 0xBC, 0x10, 0x00 };
static const u8 font5x5_font_char_71[] = { 0x3F, 0xE4, 0xF8, 0x01 };
static const u8 font5x5_font_char_72[] = { 0x31, 0xFE, 0x18, 0x01 };
static const u8 font5x5_font_char_73[] = { 0x9F, 0x10, 0xF2, 0x01 };
static const u8 font5x5_font_char_74[] = { 0x18, 0xC2, 0xF8, 0x01 };
static const u8 font5x5_font_char_75[] = { 0x31, 0x9D, 0x14, 0x01 };
static const u8 font5x5_font_char_76[] = { 0x21, 0x84, 0xF0, 0x01 };
static const u8 font5x5_font_char_77[] = { 0x71, 0xD7, 0x18, 0x01 };
static const u8 font5x5_font_char_78[] = { 0x71, 0xD6, 0x1C, 0x01 };
static const u8 font5x5_font_char_79[] = { 0x2E, 0xC6, 0xE8, 0x00 };
static const u8 font5x5_font_char_80[] = { 0x2F, 0xBE, 0x10, 0x00 };
static const u8 font5x5_font_char_81[] = { 0x3F, 0xC6, 0x4F, 0x00 };
static const u8 font5x5_font_char_82[] = { 0x2F, 0xBE, 0x18, 0x01 };
static const u8 font5x5_font_char_83[] = { 0x3F, 0x7C, 0xF8, 0x01 };
static const u8 font5x5_font_char_84[] = { 0x9F, 0x10, 0x42, 0x00 };
static const u8 font5x5_font_char_85[] = { 0x31, 0xC6, 0xF8, 0x01 };
static const u8 font5x5_font_char_86[] = { 0x31, 0x2A, 0x45, 0x00 };
static const u8 font5x5_font_char_87[] = { 0x31, 0xD6, 0xAA, 0x00 };
static const u8 font5x5_font_char_88[] = { 0x51, 0x11, 0x15, 0x01 };
static const u8 font5x5_font_char_89[] = { 0x31, 0x2A, 0x42, 0x00 };
static const u8 font5x5_font_char_90[] = { 0x1F, 0x11, 0xF1, 0x01 };
static const u8 font5x5_font_char_91[] = { 0x57, 0x03 };
static const u8 font5x5_font_char_92[] = { 0x89, 0x48 };
static const u8 font5x5_font_char_93[] = { 0xAB, 0x03 };
static const u8 font5x5_font_char_94[] = { 0x2A };
static const u8 font5x5_font_char_95[] = { 0x00, 0x00, 0x00, 0x3F };
static const u8 font5x5_font_char_96[] = { 0x09 };
static const u8 font5x5_font_char_97[] = { 0x3F, 0xC6, 0x1F, 0x01 };
static const u8 font5x5_font_char_98[] = { 0x3F, 0xBE, 0xF8, 0x01 };
static const u8 font5x5_font_char_99[] = { 0x3F, 0x84, 0xF0, 0x01 };
static const u8 font5x5_font_char_100[] = { 0x2F, 0xC6, 0xF8, 0x00 };
static const u8 font5x5_font_char_101[] = { 0x3F, 0xBC, 0xF0, 0x01 };
static const u8 font5x5_font_char_102[] = { 0x3F, 0xBC, 0x10, 0x00 };
static const u8 font5x5_font_char_103[] = { 0x3F, 0xE4, 0xF8, 0x01 };
static const u8 font5x5_font_char_104[] = { 0x31, 0xFE, 0x18, 0x01 };
static const u8 font5x5_font_char_105[] = { 0x9F, 0x10, 0xF2, 0x01 };
static const u8 font5x5_font_char_106[] = { 0x18, 0xC2, 0xF8, 0x01 };
static const u8 font5x5_font_char_107[] = { 0x31, 0x9D, 0x14, 0x01 };
static const u8 font5x5_font_char_108[] = { 0x21, 0x84, 0xF0, 0x01 };
static const u8 font5x5_font_char_109[] = { 0x71, 0xD7, 0x18, 0x01 };
static const u8 font5x5_font_char_110[] = { 0x71, 0xD6, 0x1C, 0x01 };
static const u8 font5x5_font_char_111[] = { 0x2E, 0xC6, 0xE8, 0x00 };
static const u8 font5x5_font_char_112[] = { 0x2F, 0xBE, 0x10, 0x00 };
static const u8 font5x5_font_char_113[] = { 0x3F, 0xC6, 0x4F, 0x00 };
static const u8 font5x5_font_char_114[] = { 0x2F, 0xBE, 0x18, 0x01 };
static const u8 font5x5_font_char_115[] = { 0x3F, 0x7C, 0xF8, 0x01 };
static const u8 font5x5_font_char_116[] = { 0x9F, 0x10, 0x42, 0x00 };
static const u8 font5x5_font_char_117[] = { 0x31, 0xC6, 0xF8, 0x01 };
static const u8 font5x5_font_char_118[] = { 0x31, 0x2A, 0x45, 0x00 };
static const u8 font5x5_font_char_119[] = { 0x31, 0xD6, 0xAA, 0x00 };
static const u8 font5x5_font_char_120[] = { 0x51, 0x11, 0x15, 0x01 };
static const u8 font5x5_font_char_121[] = { 0x31, 0x2A, 0x42, 0x00 };
static const u8 font5x5_font_char_122[] = { 0x1F, 0x11, 0xF1, 0x01 };
static const u8 font5x5_font_char_123[] = { 0xD6, 0x64 };
static const u8 font5x5_font_char_124[] = { 0x1B };
static const u8 font5x5_font_char_125[] = { 0x93, 0x35 };
static const u8 font5x5_font_char_126[] = { 0xA0, 0x05 };
static const u8 font5x5_font_char_127[] = { 0x00 };

static const FONT_CHAR font5x5_chars[] = 
{
 { 32, 1, 1, font5x5_font_char_32 },
 { 33, 1, 5, font5x5_font_char_33 },
 { 34, 3, 2, font5x5_font_char_34 },
 { 35, 5, 5, font5x5_font_char_35 },
 { 36, 5, 7, font5x5_font_char_36 },
 { 37, 5, 5, font5x5_font_char_37 },
 { 38, 5, 5, font5x5_font_char_38 },
 { 39, 1, 2, font5x5_font_char_39 },
 { 40, 2, 5, font5x5_font_char_40 },
 { 41, 2, 5, font5x5_font_char_41 },
 { 42, 3, 3, font5x5_font_char_42 },
 { 43, 5, 5, font5x5_font_char_43 },
 { 44, 1, 5, font5x5_font_char_44 },
 { 45, 5, 3, font5x5_font_char_45 },
 { 46, 1, 5, font5x5_font_char_46 },
 { 47, 3, 5, font5x5_font_char_47 },
 { 48, 5, 5, font5x5_font_char_48 },
 { 49, 3, 5, font5x5_font_char_49 },
 { 50, 5, 5, font5x5_font_char_50 },
 { 51, 5, 5, font5x5_font_char_51 },
 { 52, 5, 5, font5x5_font_char_52 },
 { 53, 5, 5, font5x5_font_char_53 },
 { 54, 5, 5, font5x5_font_char_54 },
 { 55, 5, 5, font5x5_font_char_55 },
 { 56, 5, 5, font5x5_font_char_56 },
 { 57, 5, 5, font5x5_font_char_57 },
 { 58, 1, 5, font5x5_font_char_58 },
 { 59, 1, 6, font5x5_font_char_59 },
 { 60, 3, 5, font5x5_font_char_60 },
 { 61, 5, 4, font5x5_font_char_61 },
 { 62, 3, 5, font5x5_font_char_62 },
 { 63, 4, 5, font5x5_font_char_63 },
 { 64, 5, 5, font5x5_font_char_64 },
 { 65, 5, 5, font5x5_font_char_65 },
 { 66, 5, 5, font5x5_font_char_66 },
 { 67, 5, 5, font5x5_font_char_67 },
 { 68, 5, 5, font5x5_font_char_68 },
 { 69, 5, 5, font5x5_font_char_69 },
 { 70, 5, 5, font5x5_font_char_70 },
 { 71, 5, 5, font5x5_font_char_71 },
 { 72, 5, 5, font5x5_font_char_72 },
 { 73, 5, 5, font5x5_font_char_73 },
 { 74, 5, 5, font5x5_font_char_74 },
 { 75, 5, 5, font5x5_font_char_75 },
 { 76, 5, 5, font5x5_font_char_76 },
 { 77, 5, 5, font5x5_font_char_77 },
 { 78, 5, 5, font5x5_font_char_78 },
 { 79, 5, 5, font5x5_font_char_79 },
 { 80, 5, 5, font5x5_font_char_80 },
 { 81, 5, 5, font5x5_font_char_81 },
 { 82, 5, 5, font5x5_font_char_82 },
 { 83, 5, 5, font5x5_font_char_83 },
 { 84, 5, 5, font5x5_font_char_84 },
 { 85, 5, 5, font5x5_font_char_85 },
 { 86, 5, 5, font5x5_font_char_86 },
 { 87, 5, 5, font5x5_font_char_87 },
 { 88, 5, 5, font5x5_font_char_88 },
 { 89, 5, 5, font5x5_font_char_89 },
 { 90, 5, 5, font5x5_font_char_90 },
 { 91, 2, 5, font5x5_font_char_91 },
 { 92, 3, 5, font5x5_font_char_92 },
 { 93, 2, 5, font5x5_font_char_93 },
 { 94, 3, 2, font5x5_font_char_94 },
 { 95, 6, 5, font5x5_font_char_95 },
 { 96, 2, 2, font5x5_font_char_96 },
 { 97, 5, 5, font5x5_font_char_97 },
 { 98, 5, 5, font5x5_font_char_98 },
 { 99, 5, 5, font5x5_font_char_99 },
 { 100, 5, 5, font5x5_font_char_100 },
 { 101, 5, 5, font5x5_font_char_101 },
 { 102, 5, 5, font5x5_font_char_102 },
 { 103, 5, 5, font5x5_font_char_103 },
 { 104, 5, 5, font5x5_font_char_104 },
 { 105, 5, 5, font5x5_font_char_105 },
 { 106, 5, 5, font5x5_font_char_106 },
 { 107, 5, 5, font5x5_font_char_107 },
 { 108, 5, 5, font5x5_font_char_108 },
 { 109, 5, 5, font5x5_font_char_109 },
 { 110, 5, 5, font5x5_font_char_110 },
 { 111, 5, 5, font5x5_font_char_111 },
 { 112, 5, 5, font5x5_font_char_112 },
 { 113, 5, 5, font5x5_font_char_113 },
 { 114, 5, 5, font5x5_font_char_114 },
 { 115, 5, 5, font5x5_font_char_115 },
 { 116, 5, 5, font5x5_font_char_116 },
 { 117, 5, 5, font5x5_font_char_117 },
 { 118, 5, 5, font5x5_font_char_118 },
 { 119, 5, 5, font5x5_font_char_119 },
 { 120, 5, 5, font5x5_font_char_120 },
 { 121, 5, 5, font5x5_font_char_121 },
 { 122, 5, 5, font5x5_font_char_122 },
 { 123, 3, 5, font5x5_font_char_123 },
 { 124, 1, 5, font5x5_font_char_124 },
 { 125, 3, 5, font5x5_font_char_125 },
 { 126, 4, 3, font5x5_font_char_126 },
 { 127, 1, 1, font5x5_font_char_127 },
};

const FONT font5x5_font = { 96, font5x5_chars };
