// Autogenerated source file
// DO NOT MODIFY

#include "font.h"

static const u8 pzim3x5_font_char_32[] = { 0x00 };
static const u8 pzim3x5_font_char_33[] = { 0x17 };
static const u8 pzim3x5_font_char_34[] = { 0x2D };
static const u8 pzim3x5_font_char_35[] = { 0x7D, 0x5F };
static const u8 pzim3x5_font_char_36[] = { 0x5A, 0x2D };
static const u8 pzim3x5_font_char_37[] = { 0xA5, 0x52 };
static const u8 pzim3x5_font_char_38[] = { 0xAA, 0x6A };
static const u8 pzim3x5_font_char_39[] = { 0x03 };
static const u8 pzim3x5_font_char_40[] = { 0x56, 0x02 };
static const u8 pzim3x5_font_char_41[] = { 0xA9, 0x01 };
static const u8 pzim3x5_font_char_42[] = { 0x55, 0x01 };
static const u8 pzim3x5_font_char_43[] = { 0xD0, 0x05 };
static const u8 pzim3x5_font_char_44[] = { 0x80, 0x03 };
static const u8 pzim3x5_font_char_45[] = { 0xC0, 0x01 };
static const u8 pzim3x5_font_char_46[] = { 0x10 };
static const u8 pzim3x5_font_char_47[] = { 0xA4, 0xA4, 0x04 };
static const u8 pzim3x5_font_char_48[] = { 0x6F, 0x7B };
static const u8 pzim3x5_font_char_49[] = { 0x9A, 0x74 };
static const u8 pzim3x5_font_char_50[] = { 0xA7, 0x72 };
static const u8 pzim3x5_font_char_51[] = { 0xA7, 0x79 };
static const u8 pzim3x5_font_char_52[] = { 0xED, 0x49 };
static const u8 pzim3x5_font_char_53[] = { 0xCF, 0x79 };
static const u8 pzim3x5_font_char_54[] = { 0xCF, 0x7B };
static const u8 pzim3x5_font_char_55[] = { 0xA7, 0x24 };
static const u8 pzim3x5_font_char_56[] = { 0xEF, 0x7B };
static const u8 pzim3x5_font_char_57[] = { 0xEF, 0x79 };
static const u8 pzim3x5_font_char_58[] = { 0x0A };
static const u8 pzim3x5_font_char_59[] = { 0x82, 0x03 };
static const u8 pzim3x5_font_char_60[] = { 0x54, 0x44 };
static const u8 pzim3x5_font_char_61[] = { 0x38, 0x0E };
static const u8 pzim3x5_font_char_62[] = { 0x11, 0x15 };
static const u8 pzim3x5_font_char_63[] = { 0xA7, 0x20 };
static const u8 pzim3x5_font_char_64[] = { 0x6F, 0x73 };
static const u8 pzim3x5_font_char_65[] = { 0xEF, 0x5B };
static const u8 pzim3x5_font_char_66[] = { 0xEF, 0x7A };
static const u8 pzim3x5_font_char_67[] = { 0x4F, 0x72 };
static const u8 pzim3x5_font_char_68[] = { 0x6B, 0x3B };
static const u8 pzim3x5_font_char_69[] = { 0xCF, 0x72 };
static const u8 pzim3x5_font_char_70[] = { 0xCF, 0x12 };
static const u8 pzim3x5_font_char_71[] = { 0x4F, 0x7B };
static const u8 pzim3x5_font_char_72[] = { 0xED, 0x5B };
static const u8 pzim3x5_font_char_73[] = { 0x97, 0x74 };
static const u8 pzim3x5_font_char_74[] = { 0x24, 0x7B };
static const u8 pzim3x5_font_char_75[] = { 0xED, 0x5A };
static const u8 pzim3x5_font_char_76[] = { 0x49, 0x72 };
static const u8 pzim3x5_font_char_77[] = { 0x7D, 0x5B };
static const u8 pzim3x5_font_char_78[] = { 0xEC, 0x1B };
static const u8 pzim3x5_font_char_79[] = { 0x6F, 0x7B };
static const u8 pzim3x5_font_char_80[] = { 0xEF, 0x13 };
static const u8 pzim3x5_font_char_81[] = { 0x6F, 0x7B, 0x02 };
static const u8 pzim3x5_font_char_82[] = { 0xEB, 0x5A };
static const u8 pzim3x5_font_char_83[] = { 0xCF, 0x79 };
static const u8 pzim3x5_font_char_84[] = { 0x97, 0x24 };
static const u8 pzim3x5_font_char_85[] = { 0x6D, 0x7B };
static const u8 pzim3x5_font_char_86[] = { 0x6D, 0x2B };
static const u8 pzim3x5_font_char_87[] = { 0x6D, 0x5F };
static const u8 pzim3x5_font_char_88[] = { 0xAD, 0x5A };
static const u8 pzim3x5_font_char_89[] = { 0xAD, 0x24 };
static const u8 pzim3x5_font_char_90[] = { 0xA7, 0x72 };
static const u8 pzim3x5_font_char_91[] = { 0x57, 0x03 };
static const u8 pzim3x5_font_char_92[] = { 0x89, 0x24, 0x12 };
static const u8 pzim3x5_font_char_93[] = { 0xAB, 0x03 };
static const u8 pzim3x5_font_char_94[] = { 0x2A };
static const u8 pzim3x5_font_char_95[] = { 0x00, 0x70 };
static const u8 pzim3x5_font_char_96[] = { 0x09 };
static const u8 pzim3x5_font_char_97[] = { 0xEF, 0x5B };
static const u8 pzim3x5_font_char_98[] = { 0xEF, 0x7A };
static const u8 pzim3x5_font_char_99[] = { 0x4F, 0x72 };
static const u8 pzim3x5_font_char_100[] = { 0x6B, 0x3B };
static const u8 pzim3x5_font_char_101[] = { 0xCF, 0x72 };
static const u8 pzim3x5_font_char_102[] = { 0xCF, 0x12 };
static const u8 pzim3x5_font_char_103[] = { 0x4F, 0x7B };
static const u8 pzim3x5_font_char_104[] = { 0xED, 0x5B };
static const u8 pzim3x5_font_char_105[] = { 0x97, 0x74 };
static const u8 pzim3x5_font_char_106[] = { 0x24, 0x7B };
static const u8 pzim3x5_font_char_107[] = { 0xED, 0x5A };
static const u8 pzim3x5_font_char_108[] = { 0x49, 0x72 };
static const u8 pzim3x5_font_char_109[] = { 0x7D, 0x5B };
static const u8 pzim3x5_font_char_110[] = { 0xEC, 0x1B };
static const u8 pzim3x5_font_char_111[] = { 0x6F, 0x7B };
static const u8 pzim3x5_font_char_112[] = { 0xEF, 0x13 };
static const u8 pzim3x5_font_char_113[] = { 0x6F, 0x7B, 0x02 };
static const u8 pzim3x5_font_char_114[] = { 0xEB, 0x5A };
static const u8 pzim3x5_font_char_115[] = { 0xCF, 0x79 };
static const u8 pzim3x5_font_char_116[] = { 0x97, 0x24 };
static const u8 pzim3x5_font_char_117[] = { 0x6D, 0x7B };
static const u8 pzim3x5_font_char_118[] = { 0x6D, 0x2B };
static const u8 pzim3x5_font_char_119[] = { 0x6D, 0x5F };
static const u8 pzim3x5_font_char_120[] = { 0xAD, 0x5A };
static const u8 pzim3x5_font_char_121[] = { 0xAD, 0x24 };
static const u8 pzim3x5_font_char_122[] = { 0xA7, 0x72 };
static const u8 pzim3x5_font_char_123[] = { 0xD6, 0x64 };
static const u8 pzim3x5_font_char_124[] = { 0x7F };
static const u8 pzim3x5_font_char_125[] = { 0x93, 0x35 };
static const u8 pzim3x5_font_char_126[] = { 0x98, 0x01 };
static const u8 pzim3x5_font_char_127[] = { 0x00 };

static const FONT_CHAR pzim3x5_chars[] = 
{
 { 32, 1, 1, pzim3x5_font_char_32 },
 { 33, 1, 5, pzim3x5_font_char_33 },
 { 34, 3, 2, pzim3x5_font_char_34 },
 { 35, 3, 5, pzim3x5_font_char_35 },
 { 36, 3, 5, pzim3x5_font_char_36 },
 { 37, 3, 5, pzim3x5_font_char_37 },
 { 38, 3, 5, pzim3x5_font_char_38 },
 { 39, 1, 2, pzim3x5_font_char_39 },
 { 40, 2, 5, pzim3x5_font_char_40 },
 { 41, 2, 5, pzim3x5_font_char_41 },
 { 42, 3, 3, pzim3x5_font_char_42 },
 { 43, 3, 4, pzim3x5_font_char_43 },
 { 44, 2, 5, pzim3x5_font_char_44 },
 { 45, 3, 3, pzim3x5_font_char_45 },
 { 46, 1, 5, pzim3x5_font_char_46 },
 { 47, 3, 7, pzim3x5_font_char_47 },
 { 48, 3, 5, pzim3x5_font_char_48 },
 { 49, 3, 5, pzim3x5_font_char_49 },
 { 50, 3, 5, pzim3x5_font_char_50 },
 { 51, 3, 5, pzim3x5_font_char_51 },
 { 52, 3, 5, pzim3x5_font_char_52 },
 { 53, 3, 5, pzim3x5_font_char_53 },
 { 54, 3, 5, pzim3x5_font_char_54 },
 { 55, 3, 5, pzim3x5_font_char_55 },
 { 56, 3, 5, pzim3x5_font_char_56 },
 { 57, 3, 5, pzim3x5_font_char_57 },
 { 58, 1, 4, pzim3x5_font_char_58 },
 { 59, 2, 5, pzim3x5_font_char_59 },
 { 60, 3, 5, pzim3x5_font_char_60 },
 { 61, 3, 4, pzim3x5_font_char_61 },
 { 62, 3, 5, pzim3x5_font_char_62 },
 { 63, 3, 5, pzim3x5_font_char_63 },
 { 64, 3, 5, pzim3x5_font_char_64 },
 { 65, 3, 5, pzim3x5_font_char_65 },
 { 66, 3, 5, pzim3x5_font_char_66 },
 { 67, 3, 5, pzim3x5_font_char_67 },
 { 68, 3, 5, pzim3x5_font_char_68 },
 { 69, 3, 5, pzim3x5_font_char_69 },
 { 70, 3, 5, pzim3x5_font_char_70 },
 { 71, 3, 5, pzim3x5_font_char_71 },
 { 72, 3, 5, pzim3x5_font_char_72 },
 { 73, 3, 5, pzim3x5_font_char_73 },
 { 74, 3, 5, pzim3x5_font_char_74 },
 { 75, 3, 5, pzim3x5_font_char_75 },
 { 76, 3, 5, pzim3x5_font_char_76 },
 { 77, 3, 5, pzim3x5_font_char_77 },
 { 78, 3, 5, pzim3x5_font_char_78 },
 { 79, 3, 5, pzim3x5_font_char_79 },
 { 80, 3, 5, pzim3x5_font_char_80 },
 { 81, 3, 6, pzim3x5_font_char_81 },
 { 82, 3, 5, pzim3x5_font_char_82 },
 { 83, 3, 5, pzim3x5_font_char_83 },
 { 84, 3, 5, pzim3x5_font_char_84 },
 { 85, 3, 5, pzim3x5_font_char_85 },
 { 86, 3, 5, pzim3x5_font_char_86 },
 { 87, 3, 5, pzim3x5_font_char_87 },
 { 88, 3, 5, pzim3x5_font_char_88 },
 { 89, 3, 5, pzim3x5_font_char_89 },
 { 90, 3, 5, pzim3x5_font_char_90 },
 { 91, 2, 5, pzim3x5_font_char_91 },
 { 92, 3, 7, pzim3x5_font_char_92 },
 { 93, 2, 5, pzim3x5_font_char_93 },
 { 94, 3, 2, pzim3x5_font_char_94 },
 { 95, 3, 5, pzim3x5_font_char_95 },
 { 96, 2, 2, pzim3x5_font_char_96 },
 { 97, 3, 5, pzim3x5_font_char_97 },
 { 98, 3, 5, pzim3x5_font_char_98 },
 { 99, 3, 5, pzim3x5_font_char_99 },
 { 100, 3, 5, pzim3x5_font_char_100 },
 { 101, 3, 5, pzim3x5_font_char_101 },
 { 102, 3, 5, pzim3x5_font_char_102 },
 { 103, 3, 5, pzim3x5_font_char_103 },
 { 104, 3, 5, pzim3x5_font_char_104 },
 { 105, 3, 5, pzim3x5_font_char_105 },
 { 106, 3, 5, pzim3x5_font_char_106 },
 { 107, 3, 5, pzim3x5_font_char_107 },
 { 108, 3, 5, pzim3x5_font_char_108 },
 { 109, 3, 5, pzim3x5_font_char_109 },
 { 110, 3, 5, pzim3x5_font_char_110 },
 { 111, 3, 5, pzim3x5_font_char_111 },
 { 112, 3, 5, pzim3x5_font_char_112 },
 { 113, 3, 6, pzim3x5_font_char_113 },
 { 114, 3, 5, pzim3x5_font_char_114 },
 { 115, 3, 5, pzim3x5_font_char_115 },
 { 116, 3, 5, pzim3x5_font_char_116 },
 { 117, 3, 5, pzim3x5_font_char_117 },
 { 118, 3, 5, pzim3x5_font_char_118 },
 { 119, 3, 5, pzim3x5_font_char_119 },
 { 120, 3, 5, pzim3x5_font_char_120 },
 { 121, 3, 5, pzim3x5_font_char_121 },
 { 122, 3, 5, pzim3x5_font_char_122 },
 { 123, 3, 5, pzim3x5_font_char_123 },
 { 124, 1, 7, pzim3x5_font_char_124 },
 { 125, 3, 5, pzim3x5_font_char_125 },
 { 126, 3, 3, pzim3x5_font_char_126 },
 { 127, 1, 1, pzim3x5_font_char_127 },
};

const FONT pzim3x5_font = { 96, pzim3x5_chars };
