// Autogenerated source file
// DO NOT MODIFY

#include "font.h"

static const u8 type_writer_font_char_32[] = { 0x00 };
static const u8 type_writer_font_char_33[] = { 0x5F };
static const u8 type_writer_font_char_34[] = { 0x2D };
static const u8 type_writer_font_char_35[] = { 0x4A, 0x7D, 0xF5, 0x95, 0x02 };
static const u8 type_writer_font_char_36[] = { 0xC4, 0x55, 0xC3, 0xAA, 0x23};
static const u8 type_writer_font_char_37[] = { 0x73, 0x21, 0x22, 0x74, 0x06 };
static const u8 type_writer_font_char_38[] = { 0x00, 0x10, 0x59, 0x5D, 0xAF, 0x5A, 0x35 };
static const u8 type_writer_font_char_39[] = { 0x03 };
static const u8 type_writer_font_char_40[] = { 0x54, 0x12, 0x11 };
static const u8 type_writer_font_char_41[] = { 0x11, 0x49, 0x05 };
static const u8 type_writer_font_char_42[] = { 0xFF, 0xF3, 0xFE, 0x3F, 0xFE, 0xFF, 0x01 };
static const u8 type_writer_font_char_43[] = { 0x80, 0x90, 0x4F, 0x08 };
static const u8 type_writer_font_char_44[] = { 0x60 };
static const u8 type_writer_font_char_45[] = { 0x00, 0x0E };
static const u8 type_writer_font_char_46[] = { 0x40 };
static const u8 type_writer_font_char_47[] = { 0x00, 0x22, 0x22, 0x02 };
static const u8 type_writer_font_char_48[] = { 0x2E, 0xC6, 0x18, 0xA3, 0x03 };
static const u8 type_writer_font_char_49[] = { 0xC4, 0x14, 0x42, 0xC8, 0x07 };
static const u8 type_writer_font_char_50[] = { 0x2E, 0x42, 0x44, 0xC4, 0x07 };
static const u8 type_writer_font_char_51[] = { 0x2E, 0x42, 0x06, 0xA3, 0x03 };
static const u8 type_writer_font_char_52[] = { 0x98, 0xCA, 0xF8, 0x21, 0x04 };
static const u8 type_writer_font_char_53[] = { 0x3F, 0x04, 0x07, 0xA3, 0x03 };
static const u8 type_writer_font_char_54[] = { 0x2E, 0x86, 0x17, 0xA3, 0x03 };
static const u8 type_writer_font_char_55[] = { 0x1F, 0x42, 0x44, 0x44, 0x00 };
static const u8 type_writer_font_char_56[] = { 0x2E, 0x46, 0x17, 0xA3, 0x03 };
static const u8 type_writer_font_char_57[] = { 0x2E, 0x46, 0x0F, 0xA3, 0x03 };
static const u8 type_writer_font_char_58[] = { 0x14 };
static const u8 type_writer_font_char_59[] = { 0xFF, 0xF3, 0xFE, 0x3F, 0xFE, 0xFF, 0x01 };
static const u8 type_writer_font_char_60[] = { 0x48, 0x12, 0x42, 0x08 };
static const u8 type_writer_font_char_61[] = { 0xC0, 0x71 };
static const u8 type_writer_font_char_62[] = { 0x21, 0x84, 0x24, 0x01 };
static const u8 type_writer_font_char_63[] = { 0x2E, 0x42, 0x44, 0x00, 0x01 };
static const u8 type_writer_font_char_64[] = { 0xE0, 0xD7, 0xFA, 0x01 };
static const u8 type_writer_font_char_65[] = { 0x2E, 0xC6, 0x1F, 0x63, 0x04 };
static const u8 type_writer_font_char_66[] = { 0x2F, 0xC6, 0x17, 0xE3, 0x03 };
static const u8 type_writer_font_char_67[] = { 0x2E, 0x86, 0x10, 0xA2, 0x03 };
static const u8 type_writer_font_char_68[] = { 0x2F, 0xC6, 0x18, 0xE3, 0x03 };
static const u8 type_writer_font_char_69[] = { 0x3F, 0x84, 0x17, 0xC2, 0x07 };
static const u8 type_writer_font_char_70[] = { 0x3F, 0x84, 0x17, 0x42, 0x00 };
static const u8 type_writer_font_char_71[] = { 0x2E, 0x86, 0xD0, 0xA3, 0x03 };
static const u8 type_writer_font_char_72[] = { 0x31, 0xC6, 0x1F, 0x63, 0x04 };
static const u8 type_writer_font_char_73[] = { 0x9F, 0x10, 0x42, 0xC8, 0x07 };
static const u8 type_writer_font_char_74[] = { 0x9F, 0x10, 0x52, 0x8A, 0x01 };
static const u8 type_writer_font_char_75[] = { 0x31, 0x95, 0x51, 0x52, 0x04 };
static const u8 type_writer_font_char_76[] = { 0x21, 0x84, 0x10, 0xC2, 0x07 };
static const u8 type_writer_font_char_77[] = { 0x71, 0xD7, 0x18, 0x63, 0x04 };
static const u8 type_writer_font_char_78[] = { 0x71, 0xD6, 0x1C, 0x63, 0x04 };
static const u8 type_writer_font_char_79[] = { 0x2E, 0xC6, 0x18, 0xA3, 0x03 };
static const u8 type_writer_font_char_80[] = { 0x2F, 0xC6, 0x17, 0x42, 0x00 };
static const u8 type_writer_font_char_81[] = { 0x2E, 0xC6, 0x18, 0x1D, 0x04 };
static const u8 type_writer_font_char_82[] = { 0x2F, 0xC6, 0x57, 0x52, 0x04 };
static const u8 type_writer_font_char_83[] = { 0x2E, 0x06, 0x07, 0xA3, 0x03 };
static const u8 type_writer_font_char_84[] = { 0x9F, 0x10, 0x42, 0x08, 0x01 };
static const u8 type_writer_font_char_85[] = { 0x31, 0xC6, 0x18, 0xA3, 0x03 };
static const u8 type_writer_font_char_86[] = { 0x31, 0x2A, 0xA5, 0x08, 0x01 };
static const u8 type_writer_font_char_87[] = { 0x31, 0xC6, 0x5A, 0xAB, 0x02 };
static const u8 type_writer_font_char_88[] = { 0x31, 0x2A, 0xA2, 0x62, 0x04 };
static const u8 type_writer_font_char_89[] = { 0x51, 0x11, 0x42, 0x08, 0x01 };
static const u8 type_writer_font_char_90[] = { 0x1F, 0x22, 0x22, 0xC2, 0x07 };
static const u8 type_writer_font_char_91[] = { 0x4F, 0x92, 0x1C };
static const u8 type_writer_font_char_92[] = { 0x41, 0x08, 0x82, 0x20, 0x04 };
static const u8 type_writer_font_char_93[] = { 0x27, 0x49, 0x1E };
static const u8 type_writer_font_char_94[] = { 0x44, 0x45 };
static const u8 type_writer_font_char_95[] = { 0x00, 0x00, 0x00, 0xC0, 0x07 };
static const u8 type_writer_font_char_96[] = { 0xFF, 0xF3, 0xFE, 0x3F, 0xFE, 0xFF, 0x01 };
static const u8 type_writer_font_char_97[] = { 0x2E, 0xC6, 0x1F, 0x63, 0x04 };
static const u8 type_writer_font_char_98[] = { 0x2F, 0xC6, 0x17, 0xE3, 0x03 };
static const u8 type_writer_font_char_99[] = { 0x2E, 0x86, 0x10, 0xA2, 0x03 };
static const u8 type_writer_font_char_100[] = { 0x2F, 0xC6, 0x18, 0xE3, 0x03 };
static const u8 type_writer_font_char_101[] = { 0x3F, 0x84, 0x17, 0xC2, 0x07 };
static const u8 type_writer_font_char_102[] = { 0x3F, 0x84, 0x17, 0x42, 0x00 };
static const u8 type_writer_font_char_103[] = { 0x2E, 0x86, 0xD0, 0xA3, 0x03 };
static const u8 type_writer_font_char_104[] = { 0x31, 0xC6, 0x1F, 0x63, 0x04 };
static const u8 type_writer_font_char_105[] = { 0x9F, 0x10, 0x42, 0xC8, 0x07 };
static const u8 type_writer_font_char_106[] = { 0x9F, 0x10, 0x52, 0x8A, 0x01 };
static const u8 type_writer_font_char_107[] = { 0x31, 0x95, 0x51, 0x52, 0x04 };
static const u8 type_writer_font_char_108[] = { 0x21, 0x84, 0x10, 0xC2, 0x07 };
static const u8 type_writer_font_char_109[] = { 0x71, 0xD7, 0x18, 0x63, 0x04 };
static const u8 type_writer_font_char_110[] = { 0x71, 0xD6, 0x1C, 0x63, 0x04 };
static const u8 type_writer_font_char_111[] = { 0x2E, 0xC6, 0x18, 0xA3, 0x03 };
static const u8 type_writer_font_char_112[] = { 0x2F, 0xC6, 0x17, 0x42, 0x00 };
static const u8 type_writer_font_char_113[] = { 0x2E, 0xC6, 0x18, 0x1D, 0x04 };
static const u8 type_writer_font_char_114[] = { 0x2F, 0xC6, 0x57, 0x52, 0x04 };
static const u8 type_writer_font_char_115[] = { 0x2E, 0x06, 0x07, 0xA3, 0x03 };
static const u8 type_writer_font_char_116[] = { 0x9F, 0x10, 0x42, 0x08, 0x01 };
static const u8 type_writer_font_char_117[] = { 0x31, 0xC6, 0x18, 0xA3, 0x03 };
static const u8 type_writer_font_char_118[] = { 0x31, 0x2A, 0xA5, 0x08, 0x01 };
static const u8 type_writer_font_char_119[] = { 0x31, 0xC6, 0x5A, 0xAB, 0x02 };
static const u8 type_writer_font_char_120[] = { 0x31, 0x2A, 0xA2, 0x62, 0x04 };
static const u8 type_writer_font_char_121[] = { 0x51, 0x11, 0x42, 0x08, 0x01 };
static const u8 type_writer_font_char_122[] = { 0x1F, 0x22, 0x22, 0xC2, 0x07 };
static const u8 type_writer_font_char_123[] = { 0xFF, 0xF3, 0xFE, 0x3F, 0xFE, 0xFF, 0x01 };
static const u8 type_writer_font_char_124[] = { 0x7F };
static const u8 type_writer_font_char_125[] = { 0xFF, 0xF3, 0xFE, 0x3F, 0xFE, 0xFF, 0x01 };
static const u8 type_writer_font_char_126[] = { 0x00, 0x54, 0x05 };
static const u8 type_writer_font_char_127[] = { 0xFF, 0xF3, 0xFE, 0x3F, 0xFE, 0xFF, 0x01 };

static const FONT_CHAR type_writer_chars[] = 
{
 { 32, 1, 1, type_writer_font_char_32 },
 { 33, 1, 7, type_writer_font_char_33 },
 { 34, 3, 2, type_writer_font_char_34 },
 { 35, 5, 7, type_writer_font_char_35 },
 { 36, 5, 8, type_writer_font_char_36 },
 { 37, 5, 7, type_writer_font_char_37 },
 { 38, 11, 5, type_writer_font_char_38 },
 { 39, 1, 2, type_writer_font_char_39 },
 { 40, 3, 7, type_writer_font_char_40 },
 { 41, 3, 7, type_writer_font_char_41 },
 { 42, 7, 7, type_writer_font_char_42 },
 { 43, 5, 6, type_writer_font_char_43 },
 { 44, 1, 7, type_writer_font_char_44 },
 { 45, 3, 4, type_writer_font_char_45 },
 { 46, 1, 7, type_writer_font_char_46 },
 { 47, 5, 6, type_writer_font_char_47 },
 { 48, 5, 7, type_writer_font_char_48 },
 { 49, 5, 7, type_writer_font_char_49 },
 { 50, 5, 7, type_writer_font_char_50 },
 { 51, 5, 7, type_writer_font_char_51 },
 { 52, 5, 7, type_writer_font_char_52 },
 { 53, 5, 7, type_writer_font_char_53 },
 { 54, 5, 7, type_writer_font_char_54 },
 { 55, 5, 7, type_writer_font_char_55 },
 { 56, 5, 7, type_writer_font_char_56 },
 { 57, 5, 7, type_writer_font_char_57 },
 { 58, 1, 5, type_writer_font_char_58 },
 { 59, 7, 7, type_writer_font_char_59 },
 { 60, 4, 7, type_writer_font_char_60 },
 { 61, 3, 5, type_writer_font_char_61 },
 { 62, 4, 7, type_writer_font_char_62 },
 { 63, 5, 7, type_writer_font_char_63 },
 { 64, 5, 5, type_writer_font_char_64 },
 { 65, 5, 7, type_writer_font_char_65 },
 { 66, 5, 7, type_writer_font_char_66 },
 { 67, 5, 7, type_writer_font_char_67 },
 { 68, 5, 7, type_writer_font_char_68 },
 { 69, 5, 7, type_writer_font_char_69 },
 { 70, 5, 7, type_writer_font_char_70 },
 { 71, 5, 7, type_writer_font_char_71 },
 { 72, 5, 7, type_writer_font_char_72 },
 { 73, 5, 7, type_writer_font_char_73 },
 { 74, 5, 7, type_writer_font_char_74 },
 { 75, 5, 7, type_writer_font_char_75 },
 { 76, 5, 7, type_writer_font_char_76 },
 { 77, 5, 7, type_writer_font_char_77 },
 { 78, 5, 7, type_writer_font_char_78 },
 { 79, 5, 7, type_writer_font_char_79 },
 { 80, 5, 7, type_writer_font_char_80 },
 { 81, 5, 7, type_writer_font_char_81 },
 { 82, 5, 7, type_writer_font_char_82 },
 { 83, 5, 7, type_writer_font_char_83 },
 { 84, 5, 7, type_writer_font_char_84 },
 { 85, 5, 7, type_writer_font_char_85 },
 { 86, 5, 7, type_writer_font_char_86 },
 { 87, 5, 7, type_writer_font_char_87 },
 { 88, 5, 7, type_writer_font_char_88 },
 { 89, 5, 7, type_writer_font_char_89 },
 { 90, 5, 7, type_writer_font_char_90 },
 { 91, 3, 7, type_writer_font_char_91 },
 { 92, 5, 7, type_writer_font_char_92 },
 { 93, 3, 7, type_writer_font_char_93 },
 { 94, 5, 3, type_writer_font_char_94 },
 { 95, 5, 7, type_writer_font_char_95 },
 { 96, 7, 7, type_writer_font_char_96 },
 { 97, 5, 7, type_writer_font_char_97 },
 { 98, 5, 7, type_writer_font_char_98 },
 { 99, 5, 7, type_writer_font_char_99 },
 { 100, 5, 7, type_writer_font_char_100 },
 { 101, 5, 7, type_writer_font_char_101 },
 { 102, 5, 7, type_writer_font_char_102 },
 { 103, 5, 7, type_writer_font_char_103 },
 { 104, 5, 7, type_writer_font_char_104 },
 { 105, 5, 7, type_writer_font_char_105 },
 { 106, 5, 7, type_writer_font_char_106 },
 { 107, 5, 7, type_writer_font_char_107 },
 { 108, 5, 7, type_writer_font_char_108 },
 { 109, 5, 7, type_writer_font_char_109 },
 { 110, 5, 7, type_writer_font_char_110 },
 { 111, 5, 7, type_writer_font_char_111 },
 { 112, 5, 7, type_writer_font_char_112 },
 { 113, 5, 7, type_writer_font_char_113 },
 { 114, 5, 7, type_writer_font_char_114 },
 { 115, 5, 7, type_writer_font_char_115 },
 { 116, 5, 7, type_writer_font_char_116 },
 { 117, 5, 7, type_writer_font_char_117 },
 { 118, 5, 7, type_writer_font_char_118 },
 { 119, 5, 7, type_writer_font_char_119 },
 { 120, 5, 7, type_writer_font_char_120 },
 { 121, 5, 7, type_writer_font_char_121 },
 { 122, 5, 7, type_writer_font_char_122 },
 { 123, 7, 7, type_writer_font_char_123 },
 { 124, 1, 7, type_writer_font_char_124 },
 { 125, 7, 7, type_writer_font_char_125 },
 { 126, 5, 4, type_writer_font_char_126 },
 { 127, 7, 7, type_writer_font_char_127 },
};

const FONT type_writer_font = { 96, type_writer_chars };
