// -*- C++ -*- generated by wxGlade 0.6.3 on Sun Feb 28 15:10:07 2010

#include <wx/wx.h>
#include <wx/image.h>
#include <wx/config.h>
#include <wx/dynarray.h>
#include <pthread.h>
#include <pthread.h>

#ifndef MUXFRONTENDDIALOG_H
#define MUXFRONTENDDIALOG_H

// begin wxGlade: ::dependencies
// end wxGlade

// begin wxGlade: ::extracode

// end wxGlade

#define NUM_MAX_VPORTS        4
#define TIMER_ID              1000
#define TIMER_PERIOD_MS       50

WX_DECLARE_OBJARRAY(wxString, StringPtrArray);

class VirtualTextCtrl : public wxTextCtrl
{
public:
  VirtualTextCtrl(wxWindow* parent, wxWindowID id, const wxString& value = "", const wxPoint& pos = wxDefaultPosition, 
             const wxSize& size = wxDefaultSize, long style = 0, const wxValidator& validator = wxDefaultValidator, 
             const wxString& name = wxTextCtrlNameStr);
             
  void  OnChar( wxKeyEvent& event );
  
private:
  DECLARE_EVENT_TABLE();
};

class MuxFrontendDialog: public wxDialog {
public:
    // begin wxGlade: MuxFrontendDialog::ids
    // end wxGlade

    MuxFrontendDialog(wxWindow* parent, int id, const wxString& title, const wxArrayString& ports, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);
    virtual ~MuxFrontendDialog();
    
private:
    // begin wxGlade: MuxFrontendDialog::methods
    void set_properties();
    void do_layout();    
    // end wxGlade
    
    static const long bauds[];    
    wxConfig *m_pConfig;
    wxArrayString m_aPorts;
    bool m_fServerRunning;
    pthread_t m_mux_tid;
    wxTimer m_timer;
    
    StringPtrArray m_aProgArgs;
    const char** m_pCmdLine;
    
    void read_configuration_data();
    void write_configuration_data();
    void set_all_vport_states( bool force_false = false);
    void set_all_button_states();
    void on_server_stopped();
    void on_server_started();    

protected:
    // begin wxGlade: MuxFrontendDialog::attributes
    wxStaticBox* sizer_sermux_static_staticbox;
    wxStaticBox* sizer_rfs_static_staticbox;
    wxStaticBox* sizer_transport_static_staticbox;
    wxStaticText* label_3;
    wxComboBox* combo_tr_com_name;
    wxStaticText* label_4;
    wxComboBox* combo_tr_com_speed;
    wxTextCtrl* text_rfs_path;
    wxButton* button_rfs_choose;
    wxStaticText* label_1;
    wxStaticText* label_2;
    wxStaticText* label_5;
    wxStaticText* label_6;
    wxTextCtrl* text_vport_1;
    wxTextCtrl* text_vport_2;
    wxTextCtrl* text_vport_3;
    wxTextCtrl* text_vport_4;
    wxButton* button_exit;
    wxButton* button_start;
    wxButton* button_stop;
    wxButton* button_clear;
    VirtualTextCtrl* text_ctrl_1;
    
    // end wxGlade

    DECLARE_EVENT_TABLE();

public:
    virtual void on_choose_path(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void on_start_server_button(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void on_stop_server(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void on_clear_console(wxCommandEvent &event); // wxGlade: <event_handler>
    virtual void on_vport_changed(wxCommandEvent &event);
    virtual void on_timer(wxTimerEvent &event);
    virtual void on_textctrl_char(wxCommandEvent &event );
}; // wxGlade: end clas


#endif // MUXFRONTENDDIALOG_H
